#include <iostream>
#include <random>

int main() {
    std::mt19937 gen(std::random_device{}()); // Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(1.0, 2.0);
    for (int n = 0; n < 10; ++n)
        // Use dis to transform the random unsigned int generated by gen into a 
        // double in [1, 2). Each call to dis(gen) generates a new random double.
        std::cout << dis(gen) << ' ';
    std::cout << '\n';

    for (int i = 0; i < 10; ++i) {
        std::cout << std::uniform_int_distribution<int32_t>(1, 100)(gen) << std::endl;
    }
    for (int i = 0; i < 10; ++i) {
        std::cout << std::uniform_real_distribution<float>(1.0, 100.0)(gen) << std::endl;
    }

    return 0;
}

