workspace(name = "BazelProject")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "5b00383d08dd71f28503736db0500b6fb4dda47489ff5fc6bed42557c07c6ba9",
    strip_prefix = "rules_closure-308b05b2419edb5c8ee0471b67a40403df940149",
    urls = [
        "https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",  # 2019-06-13
    ],
)

# git_repository(
    # name = "com_github_nelhage_rules_boost",
    # commit = "11f0851ace21b791657ef5e1accbecf6034fdd63",
    # remote = "git@github.com:charles-pku-2013/bazel_boost.git",
# )
git_repository(
    name = "com_github_nelhage_rules_boost",
    remote = "git@coding.jd.com:jd_search/bazel_boost.git",
    commit = "ff3d013bc6091e845047c7b850f4fdd6ea470e65",
)
# local_repository(
    # name = "com_github_nelhage_rules_boost",
    # path = "/Users/sunchao11/Documents/Devel/jd/bazel_boost",
# )
load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")
boost_deps()

# absl
http_archive(
  name = "rules_cc",
  urls = ["https://github.com/bazelbuild/rules_cc/archive/262ebec3c2296296526740db4aefce68c80de7fa.zip"],
  strip_prefix = "rules_cc-262ebec3c2296296526740db4aefce68c80de7fa",
)
http_archive(
  name = "com_google_absl",
  urls = ["https://github.com/abseil/abseil-cpp/archive/98eb410c93ad059f9bba1bf43f5bb916fc92a5ea.zip"],
  strip_prefix = "abseil-cpp-98eb410c93ad059f9bba1bf43f5bb916fc92a5ea",
)

http_archive(
    name = "com_github_gflags_gflags",
    strip_prefix = "gflags-46f73f88b18aee341538c0dfc22b1710a6abedef",
    url = "https://github.com/gflags/gflags/archive/46f73f88b18aee341538c0dfc22b1710a6abedef.tar.gz",
)
bind(
    name = "gflags",
    actual = "@com_github_gflags_gflags//:gflags",
)

http_archive(
    name = "com_github_google_glog",
    build_file = "//thirdparty:glog.BUILD",
    strip_prefix = "glog-a6a166db069520dbbd653c97c2e5b12e08a8bb26",
    url = "https://github.com/google/glog/archive/a6a166db069520dbbd653c97c2e5b12e08a8bb26.tar.gz"
)

http_archive(
    name = "openblas",
    strip_prefix = "OpenBLAS-0.3.13",
    urls = [
        "https://github.com/xianyi/OpenBLAS/releases/download/v0.3.13/OpenBLAS-0.3.13.tar.gz",
    ],
    build_file = "//thirdparty:openblas.BUILD",
)

http_archive(
    name = "com_github_libevent_libevent",
    urls = [
        "https://github.com/libevent/libevent/archive/release-2.1.8-stable.zip",
    ],
    sha256 = "70158101eab7ed44fd9cc34e7f247b3cae91a8e4490745d9d6eb7edc184e4d96",
    strip_prefix = "libevent-release-2.1.8-stable",
    build_file = "//thirdparty:libevent.BUILD",
)
