wrk.method = "POST"
wrk.body = '{"articles" : ["China has expressed strong dissatisfaction with Japan decision to allow the visit by an official from the Taiwan region, urging Tokyo to act with caution on the Taiwan question and refrain from undermining China sovereignty. Lin Chia-lung, head of Taiwan foreign affairs department, recently made a private visit to Japan and met Japanese politicians, according to reports. China strongly deplores and firmly opposes it, Foreign Ministry spokesman Guo Jiakun told a news conference on Monday. By permitting the trip, Japan has provided a platform for Taiwan independence forces to engage in separatist activities, Guo said, calling the move a serious violation of the basic norms governing international relations and the principles of the four political documents between China and Japan. Taiwan is an inalienable part of China territory, he said. The Taiwan question lies at the heart of China core interests, and bears on the political foundation of China-Japan relations and basic trust between the two countries. This year marks the 80th anniversary of the victory in the Chinese People War of Resistance Against Japanese Aggression, the World Anti-Fascist War, and the restoration of Taiwan. Japan, which imposed colonial rule on Taiwan for half a century, bears serious historical responsibilities to the Chinese people, Guo said. He urged Japan to abide by the spirit of the four political documents between the two countries, to honor its commitments and to reflect deeply on and draw lessons from its history. Japan should also avoid harming China sovereignty in any way or sending any wrong signals to Taiwan independence separatist forces, he said. Japan should never underestimate the firm resolve, will and ability of the Chinese people to safeguard state sovereignty and territorial integrity. On Friday, Liu Jinsong, director-general of the Foreign Ministry Department of Asian Affairs, summoned Akira Yokochi, chief minister of the Japanese embassy in Beijing, to protest against Lin trip. The Chinese embassy in Tokyo also lodged solemn representations to the Japanese side on the same day. In another development, Guo urged the United States to stop political and discriminatory law enforcement targeting Chinese students and scholars, and to honor its leadership commitment to welcome Chinese nationals to study in the country. Responding to reports that another Chinese scholar was recently detained in the US, Guo called on Washington to cease engaging in the presumption of guilt and stop political manipulation. For some time, the US has overstretched the concept of national security, frequently harassed and interrogated Chinese students and researchers, and even made baseless arrests and charges, he said. Such actions, he added, violate the lawful interests of Chinese students and scholars, disrupt bilateral exchanges especially in education — and damage the US global image."], "src" : "zh", "dst" : "en"}'
-- wrk.body = '{"articles" : ["龚六堂长期研究居民收入、劳动力市场及人口 经济等话题，也曾就构建生育友好型社会、降低居民生育成本等议题向政协提交提案。在与腾讯财经的对话中，龚六堂认为，建设生育友好型社会是一 个系统、长期的工程，不可能通过一项政策或单纯的资金补贴就能完成，也不可能通过补贴就能立竿见影的提升生育率水平。", "给三岁以下的婴幼儿 每月补贴300元，是建设生育友好型社会的一个积极信号，特别是对减轻低收入人群的生育压力有很好的帮助。"], "src" : "zh", "dst" : "en"}'
-- wrk.body = '{"articles" : ["你吃饭了吗？"], "src" : "zh", "dst" : "en"}'
wrk.headers["Content-Type"] = "application/json"

response = function(status, headers, body)
    -- print(body)
    if status ~= 200 then
        print("Error: " .. status)
    end
end
