package(default_visibility = ["//visibility:public"],)

cc_library(
    name = "run_cmd",
    hdrs = [
        "run_cmd.h",
    ],
    srcs = [
        "run_cmd.cc",
    ],
    deps = [
        "@boost//:iostreams",
    ],
)

