// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: caculator.proto
// Original file comments:
//
// protoc -I. --cpp_out=. caculator.proto
// protoc -I. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` caculator.proto
#ifndef GRPC_caculator_2eproto__INCLUDED
#define GRPC_caculator_2eproto__INCLUDED

#include "caculator.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace caculator {

class Caculator final {
 public:
  static constexpr char const* service_full_name() {
    return "caculator.Caculator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status caculate(::grpc::ClientContext* context, const ::caculator::Request& request, ::caculator::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::caculator::Response>> Asynccaculate(::grpc::ClientContext* context, const ::caculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::caculator::Response>>(AsynccaculateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::caculator::Response>> PrepareAsynccaculate(::grpc::ClientContext* context, const ::caculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::caculator::Response>>(PrepareAsynccaculateRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void caculate(::grpc::ClientContext* context, const ::caculator::Request* request, ::caculator::Response* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::caculator::Response>* AsynccaculateRaw(::grpc::ClientContext* context, const ::caculator::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::caculator::Response>* PrepareAsynccaculateRaw(::grpc::ClientContext* context, const ::caculator::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status caculate(::grpc::ClientContext* context, const ::caculator::Request& request, ::caculator::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::caculator::Response>> Asynccaculate(::grpc::ClientContext* context, const ::caculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::caculator::Response>>(AsynccaculateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::caculator::Response>> PrepareAsynccaculate(::grpc::ClientContext* context, const ::caculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::caculator::Response>>(PrepareAsynccaculateRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void caculate(::grpc::ClientContext* context, const ::caculator::Request* request, ::caculator::Response* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::caculator::Response>* AsynccaculateRaw(::grpc::ClientContext* context, const ::caculator::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::caculator::Response>* PrepareAsynccaculateRaw(::grpc::ClientContext* context, const ::caculator::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_caculate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status caculate(::grpc::ServerContext* context, const ::caculator::Request* request, ::caculator::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_caculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_caculate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_caculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status caculate(::grpc::ServerContext* context, const ::caculator::Request* request, ::caculator::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcaculate(::grpc::ServerContext* context, ::caculator::Request* request, ::grpc::ServerAsyncResponseWriter< ::caculator::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_caculate<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_caculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_caculate() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithCallbackMethod_caculate<BaseClass>, ::caculator::Request, ::caculator::Response>(
          [this](::grpc::ServerContext* context,
                 const ::caculator::Request* request,
                 ::caculator::Response* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->caculate(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithCallbackMethod_caculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status caculate(::grpc::ServerContext* context, const ::caculator::Request* request, ::caculator::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void caculate(::grpc::ServerContext* context, const ::caculator::Request* request, ::caculator::Response* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_caculate<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_caculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_caculate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_caculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status caculate(::grpc::ServerContext* context, const ::caculator::Request* request, ::caculator::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_caculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_caculate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_caculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status caculate(::grpc::ServerContext* context, const ::caculator::Request* request, ::caculator::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcaculate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_caculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_caculate() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithRawCallbackMethod_caculate<BaseClass>, ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->caculate(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithRawCallbackMethod_caculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status caculate(::grpc::ServerContext* context, const ::caculator::Request* request, ::caculator::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void caculate(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_caculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_caculate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::caculator::Request, ::caculator::Response>(std::bind(&WithStreamedUnaryMethod_caculate<BaseClass>::Streamedcaculate, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_caculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status caculate(::grpc::ServerContext* context, const ::caculator::Request* request, ::caculator::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedcaculate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::caculator::Request,::caculator::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_caculate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_caculate<Service > StreamedService;
};

}  // namespace caculator


#endif  // GRPC_caculator_2eproto__INCLUDED
