cc_library(
    name = "libB",
    srcs = ["libb.cc"],
    visibility = [
        "//visibility:public",
    ],
    copts = ["-fPIC"],
    # copts = [
        # "-Wall", "-Werror", "-Wno-unused-label", "-Wno-deprecated", "-Wno-unused-variable",
        # "-fvisibility=hidden", "-fvisibility-inlines-hidden", "-fPIC",
    # ],
)
